//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormularioWeb5.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GuardarInformacion", ReplyAction="http://tempuri.org/IService2/GuardarInformacionResponse")]
        void GuardarInformacion(string nombre, string apellidos, string sexo, string email, string direccion, string ciudad, string requerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/GuardarInformacion", ReplyAction="http://tempuri.org/IService2/GuardarInformacionResponse")]
        System.Threading.Tasks.Task GuardarInformacionAsync(string nombre, string apellidos, string sexo, string email, string direccion, string ciudad, string requerimiento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : FormularioWeb5.ServiceReference2.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<FormularioWeb5.ServiceReference2.IService2>, FormularioWeb5.ServiceReference2.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GuardarInformacion(string nombre, string apellidos, string sexo, string email, string direccion, string ciudad, string requerimiento) {
            base.Channel.GuardarInformacion(nombre, apellidos, sexo, email, direccion, ciudad, requerimiento);
        }
        
        public System.Threading.Tasks.Task GuardarInformacionAsync(string nombre, string apellidos, string sexo, string email, string direccion, string ciudad, string requerimiento) {
            return base.Channel.GuardarInformacionAsync(nombre, apellidos, sexo, email, direccion, ciudad, requerimiento);
        }
    }
}
